# Generated by Django 5.2.7 on 2026-03-09 13:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(error_messages={'unique': 'A hotel with this name already exists. Please choose a different name.'}, help_text='Enter the name of the hotel.', max_length=255, unique=True, verbose_name='Hotel Name')),
                ('address', models.CharField(blank=True, help_text='Enter the address of the hotel.', max_length=255, null=True, verbose_name='Hotel Address')),
                ('city', models.CharField(blank=True, help_text='Enter the city where the hotel is located.', max_length=100, null=True, verbose_name='Hotel City')),
                ('rating', models.IntegerField(blank=True, help_text='Enter the rating of the hotel (1-5).', null=True, verbose_name='Hotel Rating')),
                ('description', models.TextField(blank=True, help_text='Enter a description of the hotel.', null=True, verbose_name='Hotel Description')),
                ('owner', models.ForeignKey(blank=True, help_text='Select the owner of the hotel.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to=settings.AUTH_USER_MODEL, verbose_name='Hotel Owner')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
