# Generated by Django 5.2.7 on 2026-03-09 18:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(help_text='e.g. "Deluxe Room"', max_length=255, verbose_name='Room title')),
                ('price_per_night', models.DecimalField(decimal_places=2, help_text='Decimal price per night.', max_digits=10, verbose_name='Price per night')),
                ('capacity', models.PositiveIntegerField(help_text='Guests count this room type can host.', verbose_name='Capacity')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='How many identical rooms of this type exist.', verbose_name='Quantity')),
                ('hotel', models.ForeignKey(help_text='Parent hotel.', on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel', verbose_name='Hotel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
