# Generated by Django 5.2.7 on 2026-03-12

from django.db import migrations


class Migration(migrations.Migration):
    """
    Move Room and Review models out of the hotels app (state-only).

    The DB tables are intentionally kept as-is:
    - hotels_room
    - hotels_review
    """

    dependencies = [
        ("hotels", "0004_review"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name="Room"),
                migrations.DeleteModel(name="Review"),
            ],
        )
    ]

