# Generated by Django 5.2.7 on 2026-05-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_move_room_review_to_apps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'Hotel', 'verbose_name_plural': 'Hotels'},
        ),
    ]
