# Generated by Django 5.2.7 on 2026-03-09 18:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0002_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_in', models.DateField(help_text='The date when the booking starts.', verbose_name='Check-in Date')),
                ('check_out', models.DateField(help_text='The date when the booking ends.', verbose_name='Check-out Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', help_text='The current status of the booking (e.g., pending, confirmed, cancelled).', max_length=20, verbose_name='Booking Status')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, help_text='The total price for the booking.', max_digits=10, verbose_name='Total Price')),
                ('room', models.ForeignKey(help_text='The room that is booked.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotels.room', verbose_name='Room')),
                ('user', models.ForeignKey(help_text='The user who made the booking.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
