# Generated by Django 5.2.7 on 2026-03-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_booking_created_at_alter_booking_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                help_text="The current status of the booking (e.g., pending, confirmed, cancelled).",
                max_length=20,
                verbose_name="Booking Status",
            ),
        ),
    ]
