# Generated by Django 5.2.7 on 2026-03-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Point Booking.room to the moved Room model (state-only).

    The underlying DB table remains `hotels_room` via `rooms.Room.Meta.db_table`.
    """

    dependencies = [
        ("rooms", "0001_move_room_state"),
        ("bookings", "0003_alter_booking_status"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="booking",
                    name="room",
                    field=models.ForeignKey(
                        help_text="The room that is booked.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="rooms.room",
                        verbose_name="Room",
                    ),
                )
            ],
        )
    ]

