# Generated by Django 5.2.7 on 2026-05-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_move_booking_room_to_rooms_app'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
    ]
